[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "docker-flexget"
version = "0.0.1"
description = ''

[tool.poetry.dependencies]
python = "3.9"
flexget = '==3.1.152'

[tool.poetry.dev-dependencies]
