name: Clear Old Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: pip install httpx python-dateutil

      - run: python clear_ghcr.py
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
