name: Clear Old Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - run: pip install httpx

      - run: python clear_ghcr.py
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
