name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flexget:current
    - name: Publish Docker Image
      run: |
        VERSION=$(cat Dockerfile |grep FLEXGET_VERSION\=|cut -f 2 -d \=)

        TAGS=(
          latest
          "$VERSION"
          $(echo $VERSION |cut -f 1-2 -d .)
          $(echo $VERSION |cut -f 1 -d .)
        )

        docker login --username trim21 --password $DOCKER_PASS

        for t in ${TAGS[*]}
        do
            docker tag flexget:current trim21/docker-flexget:${t}
            docker push trim21/docker-flexget:${t}
        done
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: ${{ github.event_name == 'push' }}