name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo VERSION=$(cat requirements.txt | grep flexget | cut -f 3 -d \=) > $GITHUB_ENV

    - name: Build the Docker image
      run: docker build "https://github.com/Flexget/Flexget.git#v${VERSION}" --tag flexget:current

    - name: Publish Docker Image
      run: |
        TAGS=(
          latest
          "$VERSION"
          $(echo $VERSION |cut -f 1-2 -d .)
          $(echo $VERSION |cut -f 1 -d .)
        )

        docker login --username trim21 --password $DOCKER_PASS

        for t in ${TAGS[*]}
        do
            docker tag flexget:current trim21/flexget:${t}
            docker push trim21/flexget:${t}
        done
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: ${{ github.event_name == 'push' }}
